ChargePoint/xcparse

- Makefile
**Change Description:** These changes allow for running make's build, install, uninstall, & clean commands in order to build the xcparse command line tool.  We're going to use this to try and build from source for xcparse rather than using a pre-built binary with Homebrew.
**Test Plan/Testing Performed:** Tested with these changes locally that the following would result in a good xcparse install & uninstall.
make install
make clean
xcparse -h
make uninstall
xcparse -h
> Add Makefile in order to build the command line tool

- Sources/xcparse/XCPParser.swift
- xcparse.xcodeproj/xcshareddata/xcschemes/xcparse.xcscheme
**Change Description:** These changes make it so that our calls to xcresulttool & other command line tools will properly escape the file path in order to support paths with spaces.
**Test Plan/Testing Performed:** Created a folder in /tmp with xcresults named with spaces as well as destination paths that included spaces in the path & ran xcparse.  Additionally tried the interactive paths.  Need to add a better testing framework with some sample xcresults so this can be automated.
> Fixes #10 xcparse doesn't support space in file names & paths

- README.md
- Sources/xcparse/Console.swift
- Sources/xcparse/XCPParser.swift
- Sources/xcparse/XCResultToolCommand.swift
**Change Description:** These changes address a few different warnings that existed in the code base about unused results or variables.  Biggest change is the loop logic to move away from some of the hard-coding in knowing how the test runs tend to set up summary objects.  Additionally, consolidated on the XCResultToolCommand and removed hand-rolled xcresulttool calls.
**Test Plan/Testing Performed:** Ran with these changes and saw the screenshots were still output as before.  This doesn't address the illegal instruction issue yet, those changes are in a separate, upcoming PR.
> Address warnings, clean up loop logic, & XCResultToolCommand consolidation

- Sources/XCParseCore/ActionTestActivitySummary.swift
- Sources/XCParseCore/ActionTestPerformanceMetricSummary.swift
- Sources/XCParseCore/ActionTestPlanRunSummaries.swift
- Sources/XCParseCore/ActionTestPlanRunSummary.swift
- Sources/XCParseCore/ActionTestSummary.swift
- Sources/XCParseCore/ActionTestSummaryGroup.swift
- Sources/XCParseCore/ActionTestableSummary.swift
- Sources/XCParseCore/ActionsInvocationRecord.swift
- Sources/XCParseCore/ActivityLogMessage.swift
- Sources/XCParseCore/ActivityLogSection.swift
- Sources/XCParseCore/ResultIssueSummaries.swift
- Sources/XCParseCore/XCPResultDecoding.swift
- Sources/xcparse/XCPParser.swift
- Tests/xcparseTests/xcparseTests.swift
**Change Description:** These changes address the strict parsing issue with non-optional arrays #16 .  If the JSON from xcresulttool did not return a key/value for the non-optional arrays, we would end up crashing with Illegal Instruction 4 keyNotFound as we were requiring to find that key.  These changes make it so that for these non-optional arrays, we see if the key is present in the JSON & use it if so.  If it isn't, we fill in with an empty array.
**Test Plan/Testing Performed:** Ran against SwiftiumTestingKit which saw this & saw correct parsing.  Also ran against our internal Xcode 10 & Xcode 11 xcresults.
> Fixes #16 keyNotFound ActionTestSummaryGroupCodingKeys subtests

- Sources/XCParseCore/ActionTestAttachment.swift
- Sources/xcparse/XCPParser.swift
- Sources/xcparse/XCResultToolCommand.swift
**Change Description:** These changes make it so that we escape various characters that are sensitive in bash when contained with double-quotes.  This should allow exporting files like the debug descriptions without seeing bash bash us about unknown commands.
**Test Plan/Testing Performed:** Tested with these changes that an XCResult with a text file with a name containing backtick and double quotes could be successfully exported.
> Address inability to export files with bash sensitive characters in filename

- Sources/xcparse/Console.swift
- Sources/xcparse/XCPParser.swift
- Sources/xcparse/XCResultToolCommand.swift
**Change Description:** These changes fix #19 where screenshots were missing from 0.3.1 on some xcresults.  The cause of this was that there was an assumption that there wouldn't be an ActionTestSummaryGroup with no subtests (since the object only contains duration & subtests) which didn't prove correct in practice.  We now do a flatMap of all the ActionTestSummaryGroup's to get their subtests for iteration rather than trying to go one-by-one with popLast.
I also took this opportunity to add a verbose mode in interactive mode where you can see the commands & JSON responses in order to provide debugging information.
**Test Plan/Testing Performed:** Tested with these changes that I can now get screenshots out of SwiftiumTestingKit when run for multiple devices.
> Address #19 screenshots missing in 0.3.1

- README.md
- Sources/XCParseCore/ActionTestAttachment.swift
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/CommandRegistry.swift
- Sources/xcparse/XCPParser.swift
- xcparse.xcodeproj/project.pbxproj
**Change Description:** These changes add a new "attachments" sub-command.  This command will by default export all attachments in the xcresult regardless of uniform type identifier (what screenshots used to be doing).  Users can provide a list of UTIs to filter with (ex. "--uti public.plain-text") to only export attachments which conform to the given UTI.  This would be useful for folks who want to get all the debug descriptions, for example.
The screenshots command has bee modified so that it'll only export image attachments & not other files such as text debug descriptions from test failures.  It does this by taking advantage of the UTI filtering & using "public.image" UTI.
**Test Plan/Testing Performed:** Tested that with these changes, I can now export attachments that conform to …
> Add attachments sub-command & allow attachment UTI filtering

- README.md
- Sources/XCParseCore/ActionTestActivitySummary.swift
- Sources/XCParseCore/ActionTestAttachment.swift
- Sources/XCParseCore/ActionTestSummary.swift
- Sources/XCParseCore/ActionTestableSummary.swift
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/ScreenshotsCommand.swift
- Sources/xcparse/XCPParser.swift
**Change Description:** These changes introduce a new option to the screenshots/attachments sub-commands of "--test" to allow for division of screenshots on an individual test status.  This allows for much nicer file structure review where screenshots from the same test can be easily seen together.  Additionally, "--activity-type" & "--test-status" have been added as additional options to allow for advanced users to filter out screenshots from failing tests (or vice versa), or get only the screenshots that the test failure asserted via the activity type of the attachment.  These are whitelists and allow for folks to figure out all the activity types they care about rather than hard-defining the rules in xcparse.
**Test Plan/Testing Performed:** Done some basic testing, but need to do a …
> Allow division by test & filtering based off test status & attachment activity type

- Sources/XCParseCore/XCPResultDecoding.swift
**Change Description:** We're not currently parsing these activity log types, but since we've already added the classes, we should add them into the result decoding so that anyone who forks the project or is using the framework can take advantage of them.
**Test Plan/Testing Performed:** N/A
> Add missing log type decoding

- README.md
- Sources/xcparse/XCPParser.swift
- Sources/xcparse/main.swift
**Change Description:** We're now at a point where interactive mode is currently more work to keep around than it is likely worth.  As part of version 1, we're going to remove the mode now that we allow for multiple options & a highly usable --help command for the various sub-commands and compatible options.
**Test Plan/Testing Performed:** Tested that with these changes, calling the old interactive mode now leads to the help usage being printed.
> Remove interactive mode

- Sources/XCParseCore/Version+XCPTooling.swift
- Sources/XCParseCore/XCResultToolCommand.swift
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/CommandRegistry.swift
- Sources/xcparse/ScreenshotsCommand.swift
- Sources/xcparse/VersionCommand.swift
- Sources/xcparse/XCPParser.swift
- xcparse.xcodeproj/project.pbxproj
**Change Description:** These changes are to help address issues with using xcparse on Xcode 11.1 and below.  Apple's xcresulttool, which we use to extract the screenshots, crashes in some versions when attempting to export out attachments to directory paths that have Unicode characters like "iPhone Xʀ" or "한국어".  This leads to the user being unable to get their screenshots & not knowing why.  
The changes here introduce the ability for xcparse to understand the version of xcresulttool & change behavior of exporting based off the versioning.  For xcresulttool versions below 15500, we change "iPhone Xʀ" to "iPhone XR" & any other non-ASCII compatible characters into their lossy ASCII conversion (often "?").  For xcresulttool 15500 or above, we continue exporting how we always have.  In all …
> [BUG] xcparse doesn't export screenshots for iPhone Xʀ on Xcode 11.1 or below

- README.md
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/CommandRegistry.swift
- Sources/xcparse/ScreenshotsCommand.swift
- Sources/xcparse/XCPParser.swift
**Change Description:** The --test-run flag named itself off of the internal implementation of xcresult's ActionTestPlanRunSummary which is used to represent the test plan configuration runs.  However, this name is not that transparent to users of xcparse unless theyre familiar with the xcresult internals.  Due to this, we should have the flag use the name users who only see the XCResult from within Xcode would expect & there Xcode always refers to it as "Configurations" of the test plan so "--test-plan-config" seems most appropriate to convey that we'll split on each test plan configuration you have in the xcresult.
**Test Plan/Testing Performed:** Ran the new flag name and was I got the correct output.  Ran with the deprecated flag & ensured I got a warning message, but still got …
> Add --test-plan-config flag & deprecate --test-run

- README.md
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/ScreenshotsCommand.swift
- Sources/xcparse/XCPParser.swift
**Change Description:** These changes implement a feature suggested in #34 to allow for sorting the screenshots/attachments based off of the language and/or region that the device ran in.  Use case for this would be for folks who want to run tests across multiple test plan configurations (perhaps because the configuration enables certain features, simulates the GPS coordinate in a particular area, etc.) but want to group the screenshots back into localization buckets for easy review by language experts/localizers.
With these changes, the new boolean flags of --language & --region have been added.  If the language flag is specified, we create folders using the language name if it was specified or use "System Default" if the language was the device's system language.  Region behaves …
> [FEATURE] Sort screenshots into language/region-based folders

- README.md
**Change Description:**
Min can also be installed via alternative dependency managers. I included the description to install it via Mint.
> Add Mint installation instructions

- Sources/XCParseCore/ActionsInvocationRecord.swift
- Sources/XCParseCore/Extensions/String+ASCII.swift
- Sources/XCParseCore/Extensions/URL+Directory.swift
- Sources/xcparse/XCPParser.swift
- Tests/xcparseTests/xcparseTests.swift
**Change Description:** This fixes #40 by putting an explicit check to see if the xcresult path exists as a directory with an Info.plist before attempting any xcresulttool attempts. If the path does not pass, an error is given to the user highlighting the input path they gave that does not appear to be an xcresult.
**Test Plan/Testing Performed:** Added unit tests to the commands to confirm the error will get shown.
> xcparse should give better error when xcresult path leads to non-xcresult

- FormatDescriptions/FormatDescriptions.md
- FormatDescriptions/xcresult-3.24.txt
- FormatDescriptions/xcresult-3.26.txt
- Sources/XCParseCore/ActionTestActivitySummary.swift
- Sources/XCParseCore/ActionTestAttachment.swift
- Sources/XCParseCore/ActionTestFailureSummary.swift
- Sources/XCParseCore/SortedKeyValueArray.swift
- Sources/XCParseCore/SortedKeyValueArrayPair.swift
- Sources/XCParseCore/SourceCode/SourceCodeContext.swift
- Sources/XCParseCore/SourceCode/SourceCodeFrame.swift
- Sources/XCParseCore/SourceCode/SourceCodeLocation.swift
- Sources/XCParseCore/SourceCode/SourceCodeSymbolInfo.swift
- Sources/XCParseCore/TestAssociatedError.swift
- Sources/XCParseCore/XCPResultDecoding.swift
**Change Description:** This fixes #50 by adding in the xcresult 3.26 data structures. It also adds back in the userInfo parsing that we removed early on in xcparse creation. This should allow for folks to get info such as the display scale from screenshot attachments. I've made a separate folder for the formatDescriptions so that we can keep track what we've added & make it easier for devs to compare and update when new Xcodes come out.
**Test Plan/Testing Performed:** Ran the existing unit tests to confirm that parsing is not regressed on them. Need to still add some Xcode 12 xcresults to double-check the new parsing.
> Add xcresult 3.26 support

- Package.resolved
- Package.swift
- Sources/XCParseCore/Console.swift
- Sources/XCParseCore/Version+XCPTooling.swift
- Sources/XCParseCore/XCResultToolCommand.swift
- Sources/xcparse/AttachmentsCommand.swift
- Sources/xcparse/CodeCoverageCommand.swift
- Sources/xcparse/Command.swift
- Sources/xcparse/CommandRegistry.swift
- Sources/xcparse/LogsCommand.swift
- Sources/xcparse/ScreenshotsCommand.swift
- Sources/xcparse/VersionCommand.swift
- Sources/xcparse/XCPParser.swift
**Change Description:** These changes fix #62. Swift 5.5 adds async/await & the Swift Package Manager 0.5.0 had an unfortunately named "await" function. The compiler did not take kindly to this & a fix is required in the SPM code [as seen done here](https://github.com/apple/swift-package-manager/commit/d48c99ced71989b607eae211704a288fd9c7179a).
In addition, SPMUtility was transitioned to TSCUtility in a new repo of [Swift Tools Core Support](https://github.com/apple/swift-tools-support-core) in late 2019/early 2020. Information about how to transition could be found in this [PR American Express did](https://github.com/americanexpress/xcprojectlint/pull/32) & [this updated blog post](https://rderik.com/blog/command-line-argument-parsing-using-swift-package-manager-s/) by @rderik.
This PR …
> [BUG] Xcparse not installing with Xcode 13.0 Beta 4 (#62)

- FormatDescriptions/xcresult-3.34.txt
- Sources/XCParseCore/ActionTestActivitySummary.swift
- Sources/XCParseCore/ActionTestAttachment.swift
- Sources/XCParseCore/ActionTestConfiguration.swift
- Sources/XCParseCore/ActionTestExpectedFailure.swift
- Sources/XCParseCore/ActionTestNoticeSummary.swift
- Sources/XCParseCore/ActionTestPerformanceMetricSummary.swift
- Sources/XCParseCore/ActionTestRepetitionPolicySummary.swift
- Sources/XCParseCore/ActionTestSummary.swift
- Sources/XCParseCore/XCPResultDecoding.swift
**Change Description:** Adds support for new properties and objects described in xcresulttool's v3.34 of the formatDescription.
**Test Plan/Testing Performed:** Need to add unit tests for the new objects. Was able to confirm that new UUID properties were parsing out properly with existing xcresult.
> Add support for xcresult v3.34 (#64)

- Makefile
- Package.swift
**Change Description:**
1. Modify Makefile to build for arm64 and x86_64 architectures.
2. Up the swift-tools-support-core version to the latest (0.2.4).
**Test Plan/Testing Performed:**
1. Built xcparse locally and confirmed that the binary is built for both architectures. Modified Bitrise workflows to conform to the new build directory structure. 
2. Created 'deploy' workflow on Bitrise to automate the release process including the universal binary in future release assets.
> [IMA-11727] Modify Makefile to build universal xcparse binary

- FormatDescriptions/xcresult-3.39.txt
- Sources/XCParseCore/ActionRecord.swift
- Sources/XCParseCore/ActionResult.swift
- Sources/XCParseCore/ActionTestNoticeSummary.swift
- Sources/XCParseCore/ActionTestSummaryIdentifiableObject.swift
- Sources/XCParseCore/ActionTestableSummary.swift
- Sources/XCParseCore/ConsoleLogItem.swift
- Sources/XCParseCore/ConsoleLogSection.swift
- Sources/XCParseCore/XCPResultDecoding.swift
- Sources/xcparse/XCPParser.swift
**Change Description:**
1. Added new properties to previously existing xcresult objects as per v3.39 changes.
2. Added new objects,`ConsoleLogItem` and `ConsoleLogSection`, as per v3.39 changes.
3. Added xcresult v3.39 format description to repo.
**Test Plan/Testing Performed:**
1. Need to add unit tests for new objects
> [IMA-12625] Updates for xcresult v3.39

- README.md
**Change Description:**
Updated the readme for previously undocumented usage of `Expected Failure` for the `test-status` flag
**Test Plan/Testing Performed:**
> add Expected Failure status to readme
